- id: '1743804334500'
  alias: <entity_3>'s Door Opens After Bedtime
  description: ''
  triggers:
  - alias: <entity_3>'s door opens
    type: opened
    device_id: e0f...001
    entity_id: 649...abc
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: time
    after: '19:45:00'
    before: '23:59:00'
    weekday:
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
    - sun
  actions:
  - parallel:
    - type: turn_off
      device_id: 165...267
      entity_id: 741...55f
      domain: remote
    - action: lifx.set_state
      metadata: {}
      data:
        power: true
        rgb_color:
        - 255
        - 0
        - 0
        brightness_pct: 15
      target:
        device_id:
        - dfd...50b
        - 921...86f
        - 83e...943
    - action: media_player.turn_off
      target:
        device_id: 06f...bfc
      data: {}
    - action: notify.mobile_app_<entity_7>
      metadata: {}
      data:
        message: "\U0001F3C3\U0001F6AA\U0001F440"
      alias: Notify <entity_6>
    - action: notify.mobile_app_<entity_9>
      metadata: {}
      data:
        message: "\U0001F3C3\U0001F6AA\U0001F440"
      alias: Notify <entity_8>
  mode: single
- id: '1745768622067'
  alias: <entity_3>'s Door Closes After Bedtime
  description: ''
  triggers:
  - type: not_opened
    device_id: e0f...001
    entity_id: 649...abc
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: time
    after: '19:45:00'
    before: '23:59:00'
    weekday:
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
    - sun
  actions:
  - parallel:
    - action: lifx.set_state
      metadata: {}
      data:
        power: true
        rgb_color:
        - 255
        - 147
        - 41
        brightness_pct: 20
      target:
        device_id:
        - dfd...50b
        - 921...86f
    - type: turn_off
      device_id: 83e...943
      entity_id: 5ca...2e5
      domain: light
    - action: notify.mobile_app_<entity_7>
      metadata: {}
      data:
        message: "\U0001F6AA\U0001F512"
      alias: Notify <entity_6>
    - device_id: 6f9...032
      domain: mobile_app
      type: notify
      message: "\U0001F6AA\U0001F512"
      alias: Notify <entity_8>
  mode: single
- id: '1747941426924'
  alias: Go to bed
  description: ''
  triggers:
  - trigger: time
    at: '21:00:00'
  conditions: []
  actions:
  - parallel:
    - type: turn_off
      device_id: 165...267
      entity_id: 741...55f
      domain: remote
    - action: media_player.turn_off
      target:
        device_id: 06f...bfc
      data: {}
  mode: single
- id: '1766852942445'
  alias: Main Suite Weekday Wake
  description: ''
  triggers:
  - trigger: time
    at: 05:40:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id:
      - light.<entity_1>s_lamp
      - light.<entity_2>s_lamp
      - light.ceiling_light
    data:
      color_temp_kelvin: 4190
      brightness_pct: 100
  mode: single
- id: '1766853485146'
  alias: <entity_4> Nighttime
  description: Turn off <entity_4>'s light for them to go to sleep.
  triggers:
  - trigger: time
    at: '19:15:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    target:
      entity_id: light.<entity_4>s_room
    data:
      transition: 60
  mode: single
- id: '1766854460562'
  alias: <entity_4> Daytime
  description: Wake up <entity_4>
  triggers:
  - trigger: time
    at: 07:15:00
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id: light.<entity_4>s_room
    data:
      color_temp_kelvin: 5205
      brightness_pct: 52
  mode: single
- id: '1766854701215'
  alias: Kitchen Light Morning
  description: Turn on the Kitchen table light for the morning.
  triggers:
  - trigger: time
    at: 05:45:00
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id: light.kitchen_table_light
    data:
      color_temp_kelvin: 4668
      brightness_pct: 100
  mode: single
- id: '1767848379827'
  alias: <entity_4> Second off
  description: Turn off <entity_4>'s light a second time to be sure.
  triggers:
  - trigger: time
    at: '20:05:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    target:
      entity_id: light.<entity_4>s_room
    data:
      transition: 60
  mode: single
- id: '1767921881819'
  alias: <entity_4> ready for bed
  description: Set to night time color
  triggers:
  - trigger: time
    at: '19:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id:
      - light.<entity_4>s_room
    data:
      color_temp_kelvin: 2500
      brightness_pct: 60
  mode: single
- id: '1769879115557'
  alias: 3D Print Complete Notification
  triggers:
  - entity_id:
    - sensor.centauri_carbon_print_status
    - sensor.centauri_carbon_2_print_status
    to: complete
    trigger: state
  actions:
  - variables:
      base_name: '{{ trigger.entity_id | replace(''sensor.'','''') | replace(''_print_status'','''')
        }}'
      notif_title: "{{ base_name | replace('_',' ') | title }} Print Done \U0001F44D"
      notif_message: 'Printed: {{ states(''input_text.'' ~ base_name ~ ''_last_file'')
        | replace(''_'','' '') | replace(''.gcode'','''') | default(''Unknown file'',
        true) }}

        '
      notif_image: '/api/image_proxy/image.{{ base_name }}_cover_image?ts={{ now().timestamp()
        }}

        '
  - data:
      title: '{{ notif_title }}'
      message: '{{ notif_message }}'
      data:
        image: '{{ notif_image }}'
    action: notify.boss_phones
  mode: parallel
- id: '1769943079478'
  alias: Cache 3D Print Filename
  triggers:
  - entity_id:
    - sensor.centauri_carbon_file_name
    - sensor.centauri_carbon_2_file_name
    trigger: state
  conditions:
  - condition: template
    value_template: "{{ trigger.to_state.state\n      not in ['unknown', 'Unknown',
      'unavailable', 'Unavailable', ''] }}\n"
  actions:
  - target:
      entity_id: "input_text.{{ trigger.entity_id\n  | replace('sensor.','')\n  |
        replace('_file_name','_last_file') }}\n"
    data:
      value: '{{ trigger.to_state.state }}'
    action: input_text.set_value
  mode: parallel
- id: '1770361925224'
  alias: 3D Print Reset Halfway Flag
  description: ''
  triggers:
  - entity_id:
    - sensor.centauri_carbon_print_status
    - sensor.centauri_carbon_2_print_status
    to: printing
    trigger: state
  actions:
  - target:
      entity_id: "input_boolean.{{ trigger.entity_id\n  | replace('sensor.','')\n
        \ | replace('_print_status','_half_notified') }}\n"
    action: input_boolean.turn_off
  mode: parallel
- id: '1770362666172'
  alias: 3D Print Halfway Notification
  triggers:
  - entity_id:
    - sensor.centauri_carbon_percent_complete
    - sensor.centauri_carbon_2_percent_complete
    above: 49
    below: 57
    trigger: numeric_state
  conditions:
  - condition: template
    value_template: '{{ states(''input_boolean.'' ~ (trigger.entity_id | replace(''sensor.'','''')
      | replace(''_percent_complete'',''_half_notified''))) == ''off'' }}

      '
  actions:
  - variables:
      base_name: '{{ trigger.entity_id | replace(''sensor.'','''') | replace(''_percent_complete'','''')
        }}'
      notif_title: "{{ base_name | replace('_',' ') | title }} — Half done printing!
        \U0001F553"
      notif_message: 'File: {{ states(''input_text.'' ~ base_name ~ ''_last_file'')
        | replace(''_'','' '') | replace(''.gcode'','''') | default(''Unknown file'',
        true) }}

        ⏳ Time remaining: {{ (states(''sensor.'' ~ base_name ~ ''_remaining_print_time''))
        | int // 60 }} hours {{ (states(''sensor.'' ~ base_name ~ ''_remaining_print_time''))
        | int % 60 }} minutes

        '
      notif_image: '/api/image_proxy/image.{{ base_name }}_cover_image?ts={{ now().timestamp()
        }}

        '
  - target:
      entity_id: input_boolean.{{ base_name }}_half_notified
    action: input_boolean.turn_on
  - data:
      title: '{{ notif_title }}'
      message: '{{ notif_message }}'
      data:
        image: '{{ notif_image }}'
    action: notify.boss_phones
  mode: parallel
- id: '1770364950375'
  alias: 3D Print Failure Alert
  triggers:
  - entity_id:
    - sensor.centauri_carbon_print_error
    - sensor.centauri_carbon_2_print_error
    - sensor.centauri_carbon_error_status_reason
    - sensor.centauri_carbon_2_error_status_reason
    trigger: state
  conditions:
  - condition: template
    value_template: '{{ trigger.to_state.state not in [''none'', ''ok'', ''unknown'',
      ''unavailable''] }}

      '
  actions:
  - variables:
      base_name: "{{ trigger.entity_id \n   | replace('sensor.', '') \n   | replace('_print_error',
        '') \n   | replace('_error_status_reason', '') }}\n"
      notif_title: '{{ base_name | replace(''_'', '' '') | title }} — Print Error
        ❌'
      notif_message: "File: {{ states('input_text.' ~ base_name ~ '_last_file') |
        replace('_',' ') | replace('.gcode','') | default('Unknown file', true) }}\n\U0001F6A8
        Error: {{ trigger.to_state.state | replace('_',' ') | title }}\n"
      notif_image: '/api/image_proxy/image.{{ base_name }}_cover_image?ts={{ now().timestamp()
        }}

        '
  - data:
      title: '{{ notif_title }}'
      message: '{{ notif_message }}'
      data:
        image: '{{ notif_image }}'
    action: notify.boss_phones
  - target:
      entity_id: input_boolean.{{ base_name }}_half_notified
    action: input_boolean.turn_off
  mode: parallel
- id: '1770365431207'
  alias: 3D Printer Light On, On Start
  description: ''
  triggers:
  - entity_id:
    - sensor.centauri_carbon_print_status
    - sensor.centauri_carbon_2_print_status
    to: printing
    trigger: state
  actions:
  - target:
      entity_id: "light.{{ trigger.entity_id\n  | replace('sensor.','')\n  | replace('_print_status','_chamber_light')
        }}\n"
    action: light.turn_on
  mode: parallel
