
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# ---------------------------
# Custom added by me below this line
# ---------------------------

template: !include custom__sensors.yaml

# Notification group for phones
notify:
  - name: boss_phones
    platform: group
    services:
      - service: mobile_app_<entity_9>
      - service: mobile_app_<entity_7>
      
      
# Dashboards
lovelace:
  dashboards:
    mobile-dashboard:
      mode: yaml
      filename: dashboards/Material-Design-3-Dynamic-Mobile-Dashboard/dashboard.yaml
      title: MD3 Mobile
      icon: mdi:cellphone